splita/prototype/urls.py
from unicodedata import name
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path
from django.views.static import serve
from django.contrib import admin
app_name = 'prototype'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/splita/', views.splita, name='splita'),
    path('fileAuthen3/', views.fileAuthen3, name='fileAuthen3'),
    path('download_file/', views.download_file, name='download_file'),
    path('myfile/', views.myfile, name='myfile'),
    path('delete/', views.delete, name='delete'),

    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

splita/splita/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', include('landing.urls')),
    path('prototype/', include('prototype.urls')),
    path('admin/', admin.site.urls),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='langing/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="landing/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='landing/password_reset_complete.html'), name='password_reset_complete'),      
    
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

splita/users/urls.py
from django.urls import path
from . import views

splita/prototype/models.py
from django.db import models
from landing.models import customuser
User = customuser

# Create your models here.


class Documents(models.Model):
    file_name = models.CharField(max_length=150, null=True)
    docfile = models.CharField(max_length=1000)
    uploaded_at = models.DateTimeField(auto_now_add=True, null=True)
    user = models.ForeignKey(customuser, on_delete=models.CASCADE, null=True)
    file_size = models.CharField(max_length=50, null=True)
    totalchunk = models.IntegerField(null=True)

splita/prototype/views.py
from datetime import datetime
import os
from urllib import response
from django.contrib import messages
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
import zipfile
from django.template import loader

from .models import Documents
import pandas as pd
from os import listdir
from os.path import isfile, join
# from django.conf import settings
from django.views.generic.base import TemplateView
from pathlib import Path
from .models import Documents
import mimetypes
from prototype import settings
from django.http import FileResponse 


# Create your views here.
#@login_required(login_url='/login')
def dashboard(request):
    return render(request, "prototype/dashboard2.html")

def fileAuthen3(request):
    documents = Documents.objects.filter(user=request.user)
    print(documents)
    return render(request, 'prototype/fileAuthen3.html',{'files': documents})

def myfile(request):
    documents = Documents.objects.filter(user=request.user)
    print(documents)
    return render(request, 'prototype/filepage.html',{'files': documents})

def delete(request):
    filename = request.GET.get('filename')
    documents = Documents.objects.filter(user=request.user,docfile=filename )
    documents.delete()
    return redirect('prototype:myfile')

def splita(request):
    if request.method == "POST":
        # this is the data in the file
        file_settings = request.FILES['selectedfile']
        # this is the file name extracted from the file and should include the file extension
        file_settings_name = file_settings.name
        # getting out the file extension from the file name
        file_ext = file_settings_name.split('.')[1]
        file_name = file_settings_name.split('.')[0]
        zip_name = file_name + str(datetime.utcnow().timestamp()).split('.')[0]
        # this is the chunk size as provided by the user
        chunk_size = int(request.POST['chunk_row_size'])
        #file_size = Path(file_settings).stat()
        # user = request.user

       # if chunk_size <= 0 or file_settings is None:
        #messages.error(request, "Fields cannot be empty!")
        # return redirect('prototype/dashboard.html')

        if file_ext in ("csv", "json"):

            if file_ext == "csv":

                data_set = pd.read_csv(file_settings, chunksize=chunk_size)
                counter = 0

                for chunk in data_set:
                    file_name1 = file_name + str(counter) + f'.{file_ext}'
                    file = chunk.to_csv(file_name1, index=False)
                    with zipfile.ZipFile(f"media/{zip_name}.zip", 'a', compression=zipfile.ZIP_DEFLATED) as zip_file:
                        zip_file.write(file_name1,file)
                    os.remove(file_name1)
                    counter += 1

                resulting_file = Documents.objects.create(docfile=f"{zip_name}.zip",user=request.user, totalchunk=counter+1)
                resulting_file.save()

                messages.info(request, "Split completed")
                return redirect('prototype:fileAuthen3')

            if file_ext == "json":
                print('file',file_settings)
                data_set = pd.read_json(file_settings, lines = True)
                counter = 0

                for chunk in data_set:
                    file_name1 = file_name + str(counter) + f'.{file_ext}'
                    file = chunk.to_json(file_name1, index=1, orient = 'record')
                    with zipfile.ZipFile(f"media/{zip_name}.zip", 'a', compression=zipfile.ZIP_DEFLATED) as zip_file:
                        zip_file.write(file_name1,file)
                    os.remove(file_name1)
                    counter += 1

                resulting_file = Documents.objects.create(docfile=f"{zip_name}.zip",user=request.user, totalchunk=counter+1)
                resulting_file.save()

                messages.info(request, "Split completed")

                return redirect(request, 'prototype:fileAuthen3')


        messages.error(
            request, "Invalid file format, Please upload a valid csv or json file")
        return redirect('dashboard')

    return render(request, 'prototype/dashboard2.html')


def download_file(request):
    # fill these variables with real values
    filename = request.GET.get('filename')
    print('settings', os.path.join(settings.MEDIA_ROOT[0],filename))
    fl_path = os.path.join(settings.MEDIA_ROOT[0],filename)


    fl = open(fl_path, 'rb')
    print('fl', fl)
    mime_type, _ = mimetypes.guess_type(fl_path)
    print('mimetype', mime_type)
    response = FileResponse(fl, content_type=mime_type)
    response['Content-Disposition'] = "attachment; filename=%s" % filename
    return response
        # filename = 'downloaded_file_name.extension'

    # fl = open(fl_path, 'r')
    # mime_type, _ = mimetypes.guess_type(fl_path)
    # response = HttpResponse(fl, content_type=mime_type)
    # response['Content-Disposition'] = "attachment; filename=%s" % filename
    # return response


#def storage(request):
    #template = loader.get_template('prototype/storage.html')
    #return HttpResponse(template.render())
    # return render(request, 'prototype/storage.html')
    #mydocuments = Document.objects.all().values()
    #template = loader.get_template('storage.html')
    # context = {
    # 'mydocuments' : mydocuments,
    # }
    # return HttpResponse(template.render(context, request))
    # return render(request, (output))

# class MyFilesView(TemplateView):

#     template_name = "auth3.html"

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)

#         # List of files in your MEDIA_ROOT
#         media_path = settings.MEDIA_ROOT
#         myfiles = [f for f in listdir(media_path) if isfile(join(media_path, f))]
#         context['myfiles'] = myfiles

#         return context

splita/templates/prototype/auth3.html
{% extends 'prototype/base_dashboard.html' %}
{% load static %}

{% block title %}login{% endblock %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    {% for myfile in myfiles %}
      <p>{{myfile}}</p>
    {% endfor %}
</form>

{% endblock %}

splita/templates/prototype/base_dashboard.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}base{% endblock %}</title>
        <link href="{% static 'landing\css\dashboard.css' %}" rel="stylesheet">
        <link href="{% static 'landing\splita_icon\style.css' %}" rel="stylesheet">
        <script src="https://kit.fontawesome.com/c423e479ae.js" crossorigin="anonymous"></script>
        <script defer src="{% static 'landing\javascript\dashboard.js' %}"></script>

    </head>
    <body>
        <!-- container wrapping all content starts -->
        <div class="big_container">
            <!-- side navbar started -->
            <div class="side_navbar">
                <!-- brand section started -->

                <!-- LOGO DISABLE FOR DESKTOP VIEW-->
                <div class="brand brand_desktop">
                    <!-- This (The logo)leads back to home page -->
                    <a href="#"><img src="{% static 'landing\img\logo1.png' %}" class="brand_img" alt="Splita's Logo"></a>
                </div>

                <!-- ended -->
                <!-- left navbar sec started -->
                <input type="checkbox" id="check">
                    <label for="check" class="bars"><i class="fas fa-bars"></i></label>

                <nav class="left_navbar">

                    <!-- TO DISPLAY LOGO FOR MOBILE -->
                    <div class="brand ">
                        <!-- This (The logo)leads back to home page -->
                        <a href="#"><img src="{% static 'landing\img\logo1.png' %}" class="brand_img" alt="Splita's Logo"></a>
                    </div>

                    <!-- DISPLAY USER FOR MOBILE -->
                    <div class="user user_mobile">
                        <img src="{% static 'landing\img\Ellipse3.png' %}" class= "user_pic"alt="A user's Pic">
                        <div class="user_info">
                            <p class="user_text">Mary Jane</p>
                            <p class="user_text">Maryjane@gmail.com</p>
                        </div>
                    </div>
                    <ul>
                        <li class="left_list">
                            <a class= "left_link"href="{% url 'prototype:dashboard' %}">
                                <div class="splita_icon icon-dashboard"></div>
                                <p class="icon-text">Dashboard</p>
                            </a>
                        </li>

                        <li class="left_list">
                            <a class= "left_link" href="{% url 'prototype:myfile' %}">
                                <div class="splita_icon icon-file_icon"></div>
                                <p class="icon-text">My Files</p>
                            </a>
                        </li>

                        <li class="left_list">
                            <a class= "left_link"href="{% url 'prototype:fileAuthen3' %}">
                                <div class="splita_icon icon-storage_icon"></div>
                                <p class="icon-text">Storage</p>
                            </a>
                        </li>

                        <li class="left_list">
                            <a class= "left_link"href="#">
                                <div class="splita_icon icon-recycle_icon"></div>
                                <p class="icon-text">Recycle Bin</p>
                            </a>
                        </li>

                        <li class="left_list">
                            <a class= "left_link"href="#">
                                <div class="splita_icon icon-settings_icon"></div>
                                <p class="icon-text">Settings</p>
                            </a>
                        </li>

                               <!-- ended -->
                        <!-- logout sec started -->
                        <li class="left_list log_out">
                            <a class= "left_link"href="{% url 'logout' %}">
                                <div class="splita_icon icon-logout"></div>
                                <p class="icon-text">Logout</p>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <!-- Left side ended -->
            <!-- Main side started -->
            <div class="main">
                <!-- top sec started -->
                <div class="top">
                    <button class="search_btn">
                        <img src="{% static 'landing\img\searchline.png' %}" alt="Search Line">
                        <p class="search_text">Search</p>
                    </button>
                               <!-- USER DISABLE FOR MOBILE -->
                    <div class="user user_desktop">
                        <img src="{% static 'landing\img\Ellipse3.png' %}" class= "user_pic"alt="A user's Pic">
                        <div class="user_info">
                            <p class="user_text">Mary Jane</p>
                            <p class="user_text">Maryjane@gmail.com</p>
                        </div>

                        <div class="dropdown">
                            <button class="dropbtn">
                                <img src="{% static 'landing\img\user_arrow.png' %}" class= "user_arrow"alt="Arrow Down image">
                            </button>
                            <div class="dropdown-content">
                              <a href="{% url 'logout' %}">Logout</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- top ended -->
            {% block content %}

            {% endblock %}
        </div>
        <!-- container wrapping all content ended -->
        <!--<script src="./dashboard.js"></script>-->
    </body>

</html>

splita/templates/prototype/dashboard2.html
{% extends 'prototype/base_dashboard.html' %}
{% load static %}

{% block title %}Dashboard{% endblock %}
{% block content %}
    <!-- main content started -->
    <div class="main_content container">
        <!-- alone text started -->
        <h3 class="alone_text">Upload files</h3>
        <!-- alone text ended -->
        <!-- White rectangle and aside section started -->
        <form  method="post" id="drop_zone" action="splita/" enctype="multipart/form-data">
                <div class="white_aside_wrap">
                
                <div class="white_rectangle">
                                <div class="break_line_rectangle " >
                        {% csrf_token %}
                        <img src="{% static 'landing\img\file_3_line.png' %}" alt="An image that represents file">
                        <p class="main_p">Drag and drop files, or <a href="#" id= "blue_p" onclick="document.getElementById('selectedFile').click();">Browse</a></p>
                        <input type="file" id="selectedFile"  name="selectedfile" required/>
                        <h4 class="grey_capital">JSON, CSV</h4>
                        <div>
                            {% for message in messages %}
                            <p>{{message}}</p>
                            {% endfor %}
                        </div>
                <!-- break line rectangle sec ended -->
                        <h4 class="capital_text">OR IMPORT FROM</h4>
                        <ul class="social_media_wrap">
                            <li class="social_media_list google"><a href="#" class="social_media_link google">
                                <img src="{% static 'landing\img\logos_google-drive.png' %}" class= "google_img" alt="google drive logo">GOOGLE DRIVE</a></li>
                            <li class="social_media_list"><a href="#" class="social_media_link social_move2">
                                <img src="{% static 'landing\img\fontisto_dropbox.png' %}" class="social_img" alt="Dropbox logo">DROPBOX</a></li>
                            <li class="social_media_list"><a href="#" class="social_media_link social_link_mobile_bottom">
                                <img src="{% static 'landing\img\logos_microsoft-onedrive.png' %}" class="social_img" alt="one drive logo">ONE DRIVE</a></li>
                            <li class="social_media_list"><a href="#" class="social_media_link social_link_mobile_bottom2 social_move_1">
                                <img src="{% static 'landing\img\bi_link-45deg.png' %}" class="social_img" alt="google drive logo">LINK</a></li>
                        </ul>

                    </div>
            <!--white rectangle ended  -->
        </div>

            <!-- Aside sec started -->
            <aside>
                <div class="aside_content aside_content1">
                <label class="aside_text">Set chunk size</label>
                <input type="number" id="chunk_mb_size" name="chunk_mb_size" class="aside_input input_change_text" min="1" max="10" placeholder="Input number (mb)" disabled>
            </div>

                            <div class="aside_content aside_content2">
                                <label class="aside_text aside_text2">Line count per package (rows)</label>
                                <input type="number" id="chunk_row_size" name="chunk_row_size" min="0" max="3000" class="aside_input align_left" placeholder=0 required>
                            </div>
                        </aside>
                </div>
                        
                        <!-- Aside sec ended -->
                        
                        <!-- White and Aside wrap ended -->
                        <!--  Chunk button alone sec -->
                        <input class="chunk_btn" type="submit" value="CHUNK" style="text-decoration: none; color:#060CA1;"/>
    
                </form>
    </div>
    <!-- main content started ended -->
    {% endblock %}
<!-- </div> -->

splita/templates/prototype/dashhh.html
<form action="splita/" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        <input type="file" name="file-name" id="file-name">
        <label for="file-name">
            <b>Choose a file</b><span>or drag it here</span>
        </label>
        <button type="submit">chunk</button>
    </div>
    <label for="chunksize">Chunk Size</label>
    <input type="number" name="chunksize" id="chunksize">
</form>

splita/templates/prototype/fileAuthen3.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Dashboard / File Autentication 3</title>
        <link href="{% static 'landing\css\file.css' %}" rel="stylesheet">
        <link href="{% static 'landing\splita_icon\style.css' %}" rel="stylesheet">

        <script src="{& static }"></script>
    <script src="https://kit.fontawesome.com/c423e479ae.js" crossorigin="anonymous"></script>
    <script defer src="{% static 'landing\javascript\dashboard.js' %}"></script>

    </head>
    <body>
        <!-- container wrapping all content starts -->
        <div class="big_container">
            <!-- side navbar started -->
            <div class="side_navbar">
                <!-- brand section started -->

                <!-- LOGO DISABLE FOR DESKTOP VIEW-->
                <div class="brand brand_desktop">
                    <!-- This (The logo)leads back to home page -->
                    <a href="#"><img src="{% static 'landing\img\logo1.png' %}" class="brand_img" alt="Splita's Logo"></a>
                </div>


                <!-- ended -->
                <!-- left navbar sec started -->
                <input type="checkbox" id="check">
                    <label for="check" class="bars">
                        <i class="fas fa-bars"></i>
                    </label>
                <nav class="left_navbar">

                    <!-- TO DISPLAY LOGO FOR MOBILE -->
                    <div class="brand ">
                        <!-- This (The logo)leads back to home page -->
                        <a href="#"><img src="{% static 'landing\img\logo1.png' %}" class="brand_img" alt="Splita's Logo"></a>
                    </div>

                    <!-- DISPLAY USER FOR MOBILE -->
                    <div class="user user_mobile">
                        <img src="{% static 'landing\img\Ellipse3.png' %}" class= "user_pic"alt="A user's Pic">
                        <div class="user_info">
                            <p class="user_text">Mary Jane</p>
                            <p class="user_text">Maryjane@gmail.com</p>
                        </div>
                    </div>
                    <ul>
                        <li class="left_list">
                            <a class= "left_link"href="{% url 'prototype:dashboard' %}">
                                <div class="splita_icon icon-dashboard"></div>
                                <p class="icon-text">Dashboard</p>
                            </a>
                        </li>

                        <li class="left_list">
                            <a class= "left_link"href="{% url 'prototype:myfile' %}">
                                <div class="splita_icon icon-file_icon"></div>
                                <p class="icon-text">My Files</p>
                            </a>
                        </li>

                        <li class="left_list">
                            <a class= "left_link"href="#">
                                <div class="splita_icon icon-storage_icon"></div>
                                <p class="icon-text">Storage</p>
                            </a>
                        </li>

                        <li class="left_list">
                            <a class= "left_link"href="#">
                                <div class="splita_icon icon-recycle_icon"></div>
                                <p class="icon-text">Recycle Bin</p>
                            </a>
                        </li>

                        <li class="left_list">
                            <a class= "left_link"href="#">
                                <div class="splita_icon icon-settings_icon"></div>
                                <p class="icon-text">Settings</p>
                            </a>
                        </li>

                               <!-- ended -->
                        <!-- logout sec started -->
                        <li class="left_list log_out log_out_authen">
                            <a class= "left_link"href="{% url 'logout' %}">
                                <div class="splita_icon icon-logout"></div>
                                <p class="icon-text">Logout</p>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
            <!-- Left side ended -->
            <!-- Main side started -->
            <div class="main">
                <!-- top sec started -->
                <div class="top">
                    <button class="search_btn">
                        <img src="{% static 'landing\img\searchline.png' %}" alt="Search Line">
                        <p class="search_text">Search</p>
                    </button>   
                               <!-- USER DISABLE FOR MOBILE -->
                    <div class="user user_desktop">
                        <img src="{% static 'landing\img\Ellipse3.png' %}" class= "user_pic"alt="A user's Pic">
                        <div class="user_info">
                            <p class="user_text">Mary Jane</p>
                            <p class="user_text">Maryjane@gmail.com</p>
                        </div>
                        
                        <div class="dropdown">
                            <button class="dropbtn"> 
                                <img src="{% static 'landing\img\user_arrow.png' %}" class= "user_arrow"alt="Arrow Down image">
                            </button>
                            <div class="dropdown-content">
                              <a href="#">Edit Profile</a>
                              <a href="#">Help</a>
                              <a href="#">Settings</a>
                              <a href="{% url 'logout' %}" class="logout_dropdown">Logout</a>

                            </div>
                          </div> 
                    </div>
                </div>
                <!-- top ended -->
               
                <!-- main file authentication content started -->
                <div class="main_authen3">
                    <p class="your_file_text">Your Files</p>

                    <div class="main_table">
                        <table>
                            <thead id="head-element">
                                <tr class="row">
                                    <th class="top_left_radius">
                                        Date
                                    </th>
                                    <th class="long-width">
                                        File Name
                                    </th>
                                    <th colspan="1">
                                        Number of files after chunking
                                    </th>
                                    <th colspan="1">
                                        Download
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for file in files %}
                                
                                <tr class="row">
                                    <td class="file_detail long-width">
                                        {{file.uploaded_at}}
                                    </td>
                                    <td class="file_detail long-width">
                                        {{file.docfile}}
                                    </td>
                                    <td class="file_detail right_td">
                                        {{file.totalchunk}}
                                    </td>
                                    <td class="file_detail right_td">
                                        <button class="download_btn btn"><a href="/prototype/download_file?filename={{file.docfile}}" style="text-decoration: none; color:white;">Download</a></button>
                                        
                                    </td>
                                </tr>
                                <!-- SECOND FILE -->
                                
                            </tbody>
                            {% endfor %}

                        </table>
                    </div>

                    <div class="btns">
                        <button class="save_btn btn">Save</button>
                    </div>


                </div>
                <!-- main file authentication content ended -->
            </div>
        </div>
        <!-- container wrapping all content ended -->
        <script src="https://code.createjs.com/1.0.0/preloadjs.min.js"></script>
        <script src="./dashboard.js"></script>
    </body>
    
</html>

splita/templates/prototype/storage.html
hello
<table>
{% for file in mydocument %}
<tr>
    <td>{{ file.id }}</td>
    <td>{{ file.file_name }}</td>
</tr>
{% endfor %}
</table>